/** Declaration file generated by dts-gen */

export const pattern: {
    any: RegExp;
    array: RegExp;
    arrjson: RegExp;
    chinese: RegExp;
    email: RegExp;
    float: RegExp;
    isjson: RegExp;
    json: RegExp;
    mobile: RegExp;
    number: RegExp;
    pass: RegExp;
    postcode: RegExp;
    qq: RegExp;
    string: RegExp;
    tel: RegExp;
    textarea: RegExp;
    url: RegExp;
    username: RegExp;
};

export function CSVToArray(data: any, delimiter: any, omitFirstRow: any): any;

export function CSVToJSON(data: any, delimiter: any): any;

export function JSONToCSV(arr: any, columns: any, delimiter: any): any;

export function RGBToHex(r: any, g: any, b: any): any;

export function addEvent(element: any, type: any, handler: any): void;

export function all(arr: any, fn: any): any;

export function any(arr: any, fn: any): any;

export function arrayToCSV(arr: any, delimiter: any): any;

export function camel2Dash(string: any): any;

export function cleanData(data: any, map: any, nullFix: any): any;

export function clearAttr(string: any): any;

export function clearBr(string: any): any;

export function clearHtml(string: any): any;

export function clearHtmlExpSN(string: any): any;

export function clearHtmlN(string: any): any;

export function clearHtmlNS(string: any): any;

export function clearHtmlTag(string: any): any;

export function client(name: any, userAgent: any): any;

export function cutCHSString(str: any, len: any, hasDot: any): any;

export function dash2Camel(string: any, ...args: any[]): any;

export function deWxJumpLink(string: any): any;

export function deWxJumpLinkOld(string: any): any;

export function debounce(fn: any, delay: any, immediate: any): any;

export function decodeBase64(input: any): any;

export function decodeUtf8(utftext: any): any;

export function delCache(name: any): void;

export function delCookie(name: any): void;

export function delSession(name: any): void;

export function delay(): any;

export function download(url: any, filename: any, type: any): void;

export function enWxJumpLink(string: any): any;

export function enWxJumpLinkOld(string: any): any;

export function encodeBase64(input: any): any;

export function encodeUtf8(string: any): any;

export function extend(target: any, ...args: any[]): any;

export function fixNumber(number: any, n: any): any;

export function formatTime(time: any, fmt: any): any;

export function formatTimeStr(time: any, fmt: any): any;

export function getAppVersion(appName: any, withappstr: any, userAgent: any): any;

export function getCHSLength(str: any): any;

export function getCache(name: any): any;

export function getCookie(name: any): any;

export function getDirParam(url: any): any;

export function getFileType(url: any): any;

export function getIsAppVersionLastest(appName: any, compareVer: any, userAgent: any): any;

export function getNumber(string: any): any;

export function getOsVersion(osName: any, withosstr: any, userAgent: any): any;

export function getParameter(name: any): any;

export function getRandomNum(min: any, max: any): any;

export function getRandomStr(len: any, widthSpecialChar: any): any;

export function getRandomStrWidthSpecialChar(len: any): any;

export function getScrollPosition(): any;

export function getSession(name: any): any;

export function getType(target: any): any;

export function getUrlParam(url: any): any;

export function getWindowSize(): any;

export function imgAdapt(imgurl: any, size: any): any;

export function imgChoose(imgurl: any): any;

export function isArray(arr: any): any;

export function isDigitals(str: any): any;

export function isExitsFunction(funcName: any): any;

export function isExitsVariable(variableName: any): any;

export function nextIndex(min: any, max: any): any;

export function openUrl(url: any): void;

export function removeEvent(element: any, type: any, handler: any): void;

export function searchTreeObject(tree: any, expression: any, keySet: any, number: any): any;

export function setCache(name: any, value: any, seconds: any): void;

export function setCookie(name: any, value: any, seconds: any, path: any, samesite: any): void;

export function setSession(name: any, value: any, seconds: any): void;

export function splitThousand(val: any): any;

export function stopBubble(e: any): any;

export function stopDefault(e: any): any;

export function textareaInsertText(obj: any, str: any): void;

export function textareaMoveToEnd(obj: any): void;

export function throttle(fn: any, delay: any, immediate: any, debounce: any, ...args: any[]): any;

export function trim(string: any, type: any): any;

export function upperFirst(string: any): any;

export function uuid(): any;

export namespace addEvent {
    const guid: number;

}

